[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
description = "A safe, reliable implementation of remove_dir_all for Windows"
include = [
    "Cargo.toml",
    "LICENCE-APACHE",
    "LICENCE-MIT",
    "src/**/*"
]
license = "MIT/Apache-2.0"
name = "remove_dir_all"
readme = "README.md"
repository = "https://github.com/Aaronepower/remove_dir_all.git"
version = "0.2.0"
keywords = ["utility", "filesystem", "remove_dir", "windows"]
categories = ["filesystem"]

[dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
